languageCode = "ja"
title = "田中博基の簡素なWebサイト"
baseURL = "https://tanaka-hiroki1989.github.io/"
theme = "m10c"

[params]
  author = "Hiroki Tanaka"
  description = "蛇が脱皮して旧い皮を捨て去るようなもの"
  customCSS = ["css/custom.css"]

